[package]
name = "file-system"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
serde = { version = "1.0.215", features = ["derive"] }
ansi_rgb = "0.2.0"
rand = "0.8.5"
bincode = "1.3.3"
lazy_static = "1.4"